name: ekko_app
description: A native-feeling Android and iOS client for Ekko Studio v1.0.3.
publish_to: none
version: 1.0.3+4
environment:
  sdk: '>=3.12.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: 1.6.0
  socket_io_client: 3.1.6
  flutter_secure_storage: 11.1.1
  shared_preferences: 2.5.5
  uuid: 4.6.0
  flutter_markdown_plus: 1.0.12
  url_launcher: 6.3.2
  record: 7.1.1
  path_provider: 2.1.6
  file_picker: 13.0.0
  image_picker: 1.2.3
  mime: 2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 6.0.0
flutter:
  uses-material-design: true
